env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - unicorn
ignorePatterns: 
  - dist/**/*
settings:
  import/resolver:
    node:
      extensions:
      - ".ts"
      moduleDirectory:
      - node_modules
      - app/
    alias:
      map:
      - - "@"
        - "./src"
      extensions:
      - ".ts"
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
  max-len:
    - error
    - code: 120
      tabWidth: 2
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  no-console:
    - error
    - allow:
      - error
  unicorn/no-array-callback-reference:
    - off
  unicorn/no-array-for-each:
    - off
  unicorn/no-array-reduce:
    - off
  unicorn/no-null:
    - off
  unicorn/prefer-module:
    - off
overrides:
  - files:
    - webpack.config.js
    rules:
      "@typescript-eslint/no-var-requires":
        - off
  
