name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  version:
    description: "The version number"
    value: ${{ steps.get-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: get-version
      run: echo "::set-output name=version::$(echo "1.2.3")"
      shell: bash
