name: pr-checks
on:
  pull_request:
    branches:
      - main
      - tmp
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --production=false
      - name: Check releaseable
        id: check-releaseable
        uses: ./.github/actions/get-release-type
      - name: Get version type
        run: echo "The selected color is ${{ steps.check-releaseable.outputs.versionType }}"
      - run: yarn lint:js
      - run: yarn lint:sh
      - run: yarn lint:yaml
      - run: yarn build:check
