name: release
on:
  pull_request:
    types: [closed]
    branches: 
      - main
      - tmp
jobs:
  run-checks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --production=false
      - name: Get relesae type
        id: get-releaseable
        uses: ./.github/actions/get-release-type
      - name: Get latest release
        id: get-latest-release
        uses: ./.github/actions/get-latest-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseType: ${{ steps.check-releaseable.outputs.versionType }}
      - run: yarn version --no-git-tag-version --new-version "${{ steps.get-latest-release.outputs.version }}"
      - run: yarn version --no-git-tag-version --new-version "${{ steps.check-releaseable.outputs.versionType }}"
