name: release
on:
  push:
    branches:
      - main
      - tmp
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --production=false
      - name: Check releaseable
        id: check-releaseable
        uses: ./.github/actions/get-release-type
      - name: Get version type
        run: echo "The selected color is ${{ steps.check-releaseable.outputs.versionType }}"
